### ISSUE TITLE
Update JRE install to download Unlimited Strength Jurisdiction Policy files for proper assertion de/encryption

### ISSUE THREAD

**Issue by canariecaf** [canariecaf/idp-installer-CAF#71]
In the standard JRE distribution, the cryptography is regionally limited but the Service Providers in the metadata may require higher standards of cryptography.
This is called out on the idp install page here:
https://wiki.shibboleth.net/confluence/display/IDP30/Installation

The IdP-installer when it downloads the JRE should also download the extra cryptography settings and install the appropriate jars per instructions from download here:

http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html

If you don't do the JCE tweak for Unlimited Strength Jurisdiction Policy File step, the IdP will operate normally until an SP requiring this tweak is used (such as wiki.shibboleth.net) with the following warning/error fingerprint in your logs

2015-06-05 00:00:00,605 WARN [org.opensaml.saml.saml2.profile.impl.EncryptAssertions:140] - Profile Action EncryptAssertions: Error encrypting assertion

org.opensaml.xmlsec.encryption.support.EncryptionException: Error encrypting XMLObject

    at org.opensaml.xmlsec.encryption.support.Encrypter.encryptElement(Encrypter.java:543)

Caused by: org.apache.xml.security.encryption.XMLEncryptionException: Illegal key size

    at org.apache.xml.security.encryption.XMLCipher.encryptData(XMLCipher.java:1186)

Caused by: java.security.InvalidKeyException: Illegal key size

    at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1034)

2015-06-05 00:00:00,689 - ERROR [org.opensaml.profile.action.impl.DecodeMessage:73] - Profile Action DecodeMessage: Unable to decode incoming request

Reference material on this problem: http://shibboleth.net/pipermail/users/2014-June/016098.html

**Comment by canariecaf** [comment]
This was resolved in 67775c38a87f53daac2627f234955fcd7e25c707
